### ISSUE TITLE
Add a spell checker option

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/mdbook-test#1]
From rust-lang-nursery/mdBook#141: it would be nice if the `mdbook-test` backend allowed you to run a spell checker over your document. This would most probably be activated via `book.toml` and disabled by default.

```toml
[output.test]
spell-check = true
```
